package msg

import "github.com/cgalvisleon/et/envar"

var (
	MSG_NOT_FOUND                  = "not found"
	MSG_MAX_SEGMENT_BYTES          = "maxSegmentBytes must be at least 1 MB"
	MSG_INVALID_ID_LENGTH          = "invalid id length"
	MSG_DATA_TOO_LARGE             = "data too large"
	MSG_FILE_IS_NIL                = "file is nil"
	MSG_CORRUPTED_RECORD           = "corrupted record"
	MSG_INVALID_INDEX              = "invalid index"
	MSG_INVALID_SNAPSHOT           = "invalid snapshot"
	MSG_SNAPSHOT_CORRUPTED         = "snapshot corrupted"
	MSG_INVALID_SNAPSHOT_MAGIC     = "invalid snapshot magic"
	MSG_ID_IS_REQUIRED             = "id is required"
	MSG_SCHEMA_NOT_FOUND           = "schema not found"
	MSG_MODEL_NOT_FOUND            = "model not found"
	MSG_DB_NOT_FOUND               = "database not found"
	MSG_DONT_HAVE_DATABASES        = "don't have databases"
	MSG_ARG_REQUIRED               = "argument required (%s)"
	MSG_FIELD_REQUIRED             = "field required (%s)"
	MSG_TENNANT_NOT_FOUND          = "tennant not found"
	MSG_INDEX_NOT_FOUND            = "index not found"
	MSG_INDEX_NOT_DEFINED          = "index not defined"
	MSG_RECORD_EXISTS              = "record exists"
	MSG_RECORD_NOT_FOUND           = "record not found"
	MSG_PRIMARY_KEYS_NOT_FOUND     = "primary key not found"
	MSG_FIELD_NOT_FOUND            = "field not found"
	MSG_INVALID_TYPE               = "invalid type"
	MSG_INVALID_OPERATOR           = "invalid operator"
	MSG_VIOLATE_FOREIGN_KEY        = "violate foreign key (%s)"
	MSG_FOREIGN_KEY_NOT_FOUND      = "foreign key not found"
	MSG_USER_NOT_FOUND             = "user not found"
	MSG_SERIES_NOT_FOUND           = "series not found"
	MSG_USERS_NOT_FOUND            = "users not found"
	MSG_OPERATION_NOT_ALLOW        = "operation not allow"
	MSG_INVALID_CONDITION_ONLY_ONE = "invalid condition: expected an array with exactly one element"
	MSG_TX_NOT_DEFINED             = "transaction not defined"
)

func init() {
	lang := envar.GetStr("LANG", "en")

	if lang == "es" {
		MSG_NOT_FOUND = "no encontrado"
		MSG_MAX_SEGMENT_BYTES = "maxSegmentBytes debe ser al menos 1 MB"
		MSG_INVALID_ID_LENGTH = "Longitud de ID inválida"
		MSG_DATA_TOO_LARGE = "Datos demasiado grandes"
		MSG_FILE_IS_NIL = "file es nil"
		MSG_CORRUPTED_RECORD = "registro corrupto"
		MSG_INVALID_SNAPSHOT = "snapshot inválido"
		MSG_SNAPSHOT_CORRUPTED = "snapshot corrupto"
		MSG_INVALID_SNAPSHOT_MAGIC = "magic del snapshot inválido"
		MSG_ID_IS_REQUIRED = "id es requerido"
		MSG_SCHEMA_NOT_FOUND = "schema no encontrado"
		MSG_MODEL_NOT_FOUND = "model no encontrado"
		MSG_DB_NOT_FOUND = "database no encontrado"
		MSG_DONT_HAVE_DATABASES = "no tiene databases"
		MSG_ARG_REQUIRED = "argumento requerido (%s)"
		MSG_FIELD_REQUIRED = "field requerido (%s)"
		MSG_TENNANT_NOT_FOUND = "tennant no encontrado"
		MSG_INDEX_NOT_FOUND = "index no encontrado"
		MSG_INDEX_NOT_DEFINED = "index no definido"
		MSG_RECORD_EXISTS = "record exists"
		MSG_RECORD_NOT_FOUND = "record no encontrado"
		MSG_PRIMARY_KEYS_NOT_FOUND = "primary key no encontrado"
		MSG_FIELD_NOT_FOUND = "field no encontrado"
		MSG_INVALID_TYPE = "tipo inválido"
		MSG_INVALID_OPERATOR = "operador inválido"
		MSG_VIOLATE_FOREIGN_KEY = "violación de clave foranea (%s)"
		MSG_FOREIGN_KEY_NOT_FOUND = "foreign key no encontrado"
		MSG_USER_NOT_FOUND = "usuario no encontrado"
		MSG_SERIES_NOT_FOUND = "series no encontrada"
		MSG_USERS_NOT_FOUND = "usuarios no encontrados"
		MSG_OPERATION_NOT_ALLOW = "operación no permitida"
		MSG_INVALID_CONDITION_ONLY_ONE = "condición inválida: se esperaba un array con exactamente un elemento"
		MSG_TX_NOT_DEFINED = "transacción no definida"
	}
}
